---
sg_dict:
  sg-0a3fd060:
    name: prod-jump
    rules:
    - cidr_ip: 0.0.0.0/0
      from_port: 22
      proto: tcp
      to_port: 22
    rules_egress:
    - cidr_ip: 0.0.0.0/0
      from_port: all
      proto: all
      to_port: all
    tags:
      Name: prod-jump
    vpc_id: "{{ vpc_prod['vpcs'][0]['id'] }}"
  sg-4b25ca21:
    name: prod-git
    rules:
    - cidr_ip: 10.0.0.0/20
      from_port: 1194
      proto: udp
      to_port: 1194
    - cidr_ip: 0.0.0.0/0
      from_port: 22
      proto: tcp
      to_port: 22
    - cidr_ip: 149.174.216.33/32
      from_port: 25
      proto: tcp
      to_port: 25
    - cidr_ip: 149.174.216.34/31
      from_port: 25
      proto: tcp
      to_port: 25
    - cidr_ip: 149.174.216.36/31
      from_port: 25
      proto: tcp
      to_port: 25
    - cidr_ip: 149.174.253.68/32
      from_port: 25
      proto: tcp
      to_port: 25
    - cidr_ip: 149.174.253.66/31
      from_port: 25
      proto: tcp
      to_port: 25
    - cidr_ip: 0.0.0.0/0
      from_port: 8443
      proto: tcp
      to_port: 8443
    - cidr_ip: 0.0.0.0/0
      from_port: 443
      proto: tcp
      to_port: 443
    - cidr_ip: 10.0.0.0/20
      from_port: 122
      proto: tcp
      to_port: 122
    - cidr_ip: 34.213.196.129/32
      from_port: 122
      proto: tcp
      to_port: 122
    rules_egress:
    - cidr_ip: 0.0.0.0/0
      from_port: all
      proto: all
      to_port: all
    tags: 
      Name: prod-git
    vpc_id: "{{ vpc_prod['vpcs'][0]['id'] }}"
  sg-d638d7bc:
    name: stage-jump
    rules:
    - cidr_ip: 10.0.16.0/20
      from_port: 22
      proto: tcp
      to_port: 22
    rules_egress:
    - cidr_ip: 0.0.0.0/0
      from_port: all
      proto: all
      to_port: all
    tags: 
      Name: stage-jump
    vpc_id: "{{ vpc_stage['vpcs'][0]['id'] }}"
  sg-f739d69d:
    name: stage-git
    rules: 
    - cidr_ip: 10.0.16.0/20
      from_port: 161
      proto: udp
      to_port: 161
    - cidr_ip: 10.0.16.0/20
      from_port: 1194
      proto: udp
      to_port: 1194
    - cidr_ip: 0.0.0.0/0
      from_port: 22
      proto: tcp
      to_port: 22
    - cidr_ip: 149.174.216.33/32
      from_port: 25
      proto: tcp
      to_port: 25
    - cidr_ip: 149.174.216.34/31
      from_port: 25
      proto: tcp
      to_port: 25
    - cidr_ip: 149.174.216.36/31
      from_port: 25
      proto: tcp
      to_port: 25
    - cidr_ip: 0.0.0.0/0
      from_port: 8443
      proto: tcp
      to_port: 8443
    - cidr_ip: 0.0.0.0/0
      from_port: 443
      proto: tcp
      to_port: 443
    - cidr_ip: 10.0.16.0/20
      from_port: 122
      proto: tcp
      to_port: 122
    rules_egress:
    - cidr_ip: 0.0.0.0/0
      from_port: all
      proto: all
      to_port: all
    tags:
      Name: stage-git 
    vpc_id: "{{ vpc_stage['vpcs'][0]['id'] }}"
