---
sg_dict:
  sg-010038e2c5c19f860:
    description: Bastion SSH Access
    group_id: sg-010038e2c5c19f860
    group_name: bastion-infra-BastionSecurityGroup-164G3PIYHN39Q
    rules:
    - cidr_ip: 0.0.0.0/0
      from_port: 2222
      proto: tcp
      to_port: 2222
    rules_egress:
    - cidr_ip: 0.0.0.0/0
      from_port: all
      proto: all
      to_port: all
    tags:
      Application: bastion
      Environment: infra
      Name: bastion-infra-sg
      Owner: yourteam@oath.com
      Stack: bastion
      aws:cloudformation:logical-id: BastionSecurityGroup
      aws:cloudformation:stack-id: arn:aws:cloudformation:us-east-1:808213275133:stack/bastion-infra/11f62270-0a56-11ea-bcc7-12b94cd95a93
      aws:cloudformation:stack-name: bastion-infra
    vpc_id: "{{ vpc_bastion_infra['vpcs'][0]['id'] }}"
  sg-02f3241190fa35265:
    description: creating security group jumphost
    group_id: sg-02f3241190fa35265
    group_name: jumphost
    rules: []
    rules_egress:
    - cidr_ip: 0.0.0.0/0
      from_port: all
      proto: all
      to_port: all
    tags: {}
    vpc_id: "{{ vpc_prod['vpcs'][0]['id'] }}"
  sg-058b8e8904109ff6c:
    description: creating security group VM-seal-prod
    group_id: sg-058b8e8904109ff6c
    group_name: VM-seal-prod
    rules:
    - cidr_ip: 10.1.0.0/23
      from_port: 2377
      proto: tcp
      to_port: 2377
    - cidr_ip: 10.1.0.0/23
      from_port: all
      proto: all
      to_port: all
    - cidr_ip: 216.145.54.44/32
      from_port: 22
      proto: tcp
      to_port: 22
    - cidr_ip: 209.131.62.115/32
      from_port: 22
      proto: tcp
      to_port: 22
    - cidr_ip: 216.145.54.158/32
      from_port: 22
      proto: tcp
      to_port: 22
    - cidr_ip: 209.131.62.170/32
      from_port: 22
      proto: tcp
      to_port: 22
    - cidr_ip: 216.145.54.7/32
      from_port: 22
      proto: tcp
      to_port: 22
    - cidr_ip: 216.145.54.50/32
      from_port: 22
      proto: tcp
      to_port: 22
    - cidr_ip: 209.131.62.123/32
      from_port: 22
      proto: tcp
      to_port: 22
    - cidr_ip: 192.168.0.0/26
      from_port: 22
      proto: tcp
      to_port: 22
    - cidr_ip: 34.205.80.245/32
      from_port: 22
      proto: tcp
      to_port: 22
    - cidr_ip: 54.205.215.83/32
      from_port: 22
      proto: tcp
      to_port: 22
    - cidr_ip: 10.1.0.0/23
      from_port: 22
      proto: tcp
      to_port: 22
    - from_port: 22
      group_id: sg-010038e2c5c19f860
      proto: tcp
      to_port: 22
    - cidr_ip: 10.1.0.0/23
      from_port: 5443
      proto: tcp
      to_port: 5443
    - cidr_ip: 54.205.215.83/32
      from_port: 5443
      proto: tcp
      to_port: 5443
    - cidr_ip: 34.205.80.245/32
      from_port: 5443
      proto: tcp
      to_port: 5443
    - cidr_ip: 209.131.62.115/32
      from_port: 443
      proto: tcp
      to_port: 443
    - cidr_ip: 98.138.3.86/32
      from_port: 443
      proto: tcp
      to_port: 443
    - cidr_ip: 209.131.62.115/32
      from_port: 1024
      proto: tcp
      to_port: 65535
    - cidr_ip: 192.168.0.0/26
      from_port: 1024
      proto: tcp
      to_port: 65535
    - cidr_ip: 10.1.0.0/23
      from_port: 1024
      proto: tcp
      to_port: 65535
    - cidr_ip: 54.205.215.83/32
      from_port: 1024
      proto: tcp
      to_port: 65535
    - cidr_ip: 34.205.80.245/32
      from_port: 1024
      proto: tcp
      to_port: 65535
    - cidr_ip: 98.138.3.86/32
      from_port: 1024
      proto: tcp
      to_port: 65535
    rules_egress:
    - cidr_ip: 0.0.0.0/0
      from_port: all
      proto: all
      to_port: all
    tags:
      Name: VM-seal-Prod
    vpc_id: "{{ vpc_prod['vpcs'][0]['id'] }}"
  sg-070a9d6c76d5b7eef:
    description: creating security group VM-seal-prod-ssh-proxy
    group_id: sg-070a9d6c76d5b7eef
    group_name: VM-seal-prod-ssh-proxy
    rules:
    - cidr_ip: 69.147.96.238/32
      from_port: 0
      proto: tcp
      to_port: 65535
    - cidr_ip: 67.195.177.119/32
      from_port: all
      proto: all
      to_port: all
    - cidr_ip: 216.145.53.1/32
      from_port: 22
      proto: tcp
      to_port: 22
    - cidr_ip: 69.147.96.238/32
      from_port: 22
      proto: tcp
      to_port: 22
    - cidr_ip: 209.131.62.123/32
      from_port: 22
      proto: tcp
      to_port: 22
    - cidr_ip: 209.131.62.115/32
      from_port: 22
      proto: tcp
      to_port: 22
    - cidr_ip: 69.147.96.239/32
      from_port: 22
      proto: tcp
      to_port: 22
    - cidr_ip: 209.131.62.113/32
      from_port: 22
      proto: tcp
      to_port: 22
    - cidr_ip: 98.139.190.58/32
      from_port: 22
      proto: tcp
      to_port: 22
    - cidr_ip: 209.131.62.170/32
      from_port: 22
      proto: tcp
      to_port: 22
    - cidr_ip: 34.209.186.121/32
      from_port: 22
      proto: tcp
      to_port: 22
    - cidr_ip: 64.236.208.26/32
      from_port: 22
      proto: tcp
      to_port: 22
    - cidr_ip: 74.6.66.213/32
      from_port: 22
      proto: tcp
      to_port: 22
    - cidr_ip: 184.165.8.96/30
      from_port: 22
      proto: tcp
      to_port: 22
    - cidr_ip: 199.167.109.202/32
      from_port: 22
      proto: tcp
      to_port: 22
    - cidr_ip: 209.131.62.124/32
      from_port: 22
      proto: tcp
      to_port: 22
    - cidr_ip: 66.228.162.56/32
      from_port: 22
      proto: tcp
      to_port: 22
    - cidr_ip: 98.139.190.55/32
      from_port: 22
      proto: tcp
      to_port: 22
    - cidr_ip: 98.139.190.56/32
      from_port: 22
      proto: tcp
      to_port: 22
    - cidr_ip: 98.139.190.57/32
      from_port: 22
      proto: tcp
      to_port: 22
    - cidr_ip: 98.139.248.64/32
      from_port: 22
      proto: tcp
      to_port: 22
    - cidr_ip: 98.139.248.97/32
      from_port: 22
      proto: tcp
      to_port: 22
    - cidr_ip: 209.131.62.126/32
      from_port: 22
      proto: tcp
      to_port: 22
    - cidr_ip: 98.139.248.96/32
      from_port: 22
      proto: tcp
      to_port: 22
    - cidr_ip: 209.131.62.115/32
      from_port: 3389
      proto: tcp
      to_port: 3389
    rules_egress:
    - cidr_ip: 0.0.0.0/0
      from_port: all
      proto: all
      to_port: all
    tags:
      Name: VM-seal-Prod-SSH-Proxy
    vpc_id: "{{ vpc_prod['vpcs'][0]['id'] }}"
  sg-07ffed619510e8e66:
    description: creating security group Splunk
    group_id: sg-07ffed619510e8e66
    group_name: Splunk
    rules:
    - cidr_ip: 209.131.62.115/32
      from_port: 514
      proto: tcp
      to_port: 514
    - cidr_ip: 209.131.62.126/32
      from_port: 0
      proto: tcp
      to_port: 65535
    - cidr_ip: 209.131.62.124/32
      from_port: 0
      proto: tcp
      to_port: 65535
    - cidr_ip: 66.228.162.40/32
      from_port: 8000
      proto: tcp
      to_port: 8000
    - cidr_ip: 66.228.162.52/32
      from_port: 8000
      proto: tcp
      to_port: 8000
    - cidr_ip: 209.131.62.115/32
      from_port: 8000
      proto: tcp
      to_port: 8000
    - cidr_ip: 10.1.0.27/32
      from_port: 22
      proto: tcp
      to_port: 22
    - cidr_ip: 209.131.62.115/32
      from_port: 22
      proto: tcp
      to_port: 22
    - cidr_ip: 209.131.62.115/32
      from_port: 8089
      proto: tcp
      to_port: 8089
    - cidr_ip: 209.131.62.115/32
      from_port: 9997
      proto: tcp
      to_port: 9997
    - cidr_ip: 209.131.62.115/32
      from_port: 8088
      proto: tcp
      to_port: 8088
    - cidr_ip: 209.131.62.115/32
      from_port: 443
      proto: tcp
      to_port: 443
    rules_egress:
    - cidr_ip: 0.0.0.0/0
      from_port: all
      proto: all
      to_port: all
    tags:
      Name: Splunk
    vpc_id: "{{ vpc_prod['vpcs'][0]['id'] }}"
  sg-088df6dd9f695571f:
    description: creating security group VM-seal-nginx
    group_id: sg-088df6dd9f695571f
    group_name: VM-seal-nginx
    rules:
    - cidr_ip: 10.1.0.0/23
      from_port: all
      proto: all
      to_port: all
    - cidr_ip: 203.83.248.37/32
      from_port: 22
      proto: tcp
      to_port: 22
    - cidr_ip: 34.216.100.51/32
      from_port: 22
      proto: tcp
      to_port: 22
    - cidr_ip: 209.131.62.170/32
      from_port: 22
      proto: tcp
      to_port: 22
    - cidr_ip: 209.131.62.115/32
      from_port: 22
      proto: tcp
      to_port: 22
    - cidr_ip: 192.168.0.0/26
      from_port: 22
      proto: tcp
      to_port: 22
    - cidr_ip: 10.1.0.0/23
      from_port: 22
      proto: tcp
      to_port: 22
    - cidr_ip: 52.38.129.250/32
      from_port: 443
      proto: tcp
      to_port: 443
    - cidr_ip: 0.0.0.0/0
      from_port: 443
      proto: tcp
      to_port: 443
    - cidr_ip: 10.1.0.0/23
      from_port: 1024
      proto: tcp
      to_port: 65535
    - cidr_ip: 192.168.0.0/26
      from_port: 1024
      proto: tcp
      to_port: 65535
    rules_egress:
    - cidr_ip: 0.0.0.0/0
      from_port: all
      proto: all
      to_port: all
    tags:
      Name: VM-seal-Nginx
    vpc_id: "{{ vpc_prod['vpcs'][0]['id'] }}"
  sg-08cfb0fcbcdd2381d:
    description: default VPC security group
    group_id: sg-08cfb0fcbcdd2381d
    group_name: default
    rules: []
    rules_egress: []
    tags: {}
    vpc_id: "{{ vpc_bastion_infra['vpcs'][0]['id'] }}"
  sg-08debe5dc255ee0c6:
    description: default VPC security group
    group_id: sg-08debe5dc255ee0c6
    group_name: default
    rules: []
    rules_egress: []
    tags:
      Name: DO NOT USE
    vpc_id: "{{ vpc_bastion['vpcs'][0]['id'] }}"
  sg-09815b4ff34ca4c97:
    description: EFS security group
    group_id: sg-09815b4ff34ca4c97
    group_name: EFS-SG
    rules:
    - cidr_ip: 10.1.0.0/23
      from_port: all
      proto: all
      to_port: all
    rules_egress:
    - cidr_ip: 0.0.0.0/0
      from_port: all
      proto: all
      to_port: all
    tags: {}
    vpc_id: "{{ vpc_prod['vpcs'][0]['id'] }}"
  sg-09a8659c64a7b0b1f:
    description: default VPC security group
    group_id: sg-09a8659c64a7b0b1f
    group_name: default
    rules: []
    rules_egress: []
    tags:
      Name: EFS-sg
    vpc_id: "{{ vpc_prod['vpcs'][0]['id'] }}"
  sg-0a083d0eb36e3b156:
    description: creating security group launch-wizard-1
    group_id: sg-0a083d0eb36e3b156
    group_name: launch-wizard-1
    rules: []
    rules_egress:
    - cidr_ip: 0.0.0.0/0
      from_port: all
      proto: all
      to_port: all
    tags: {}
    vpc_id: "{{ vpc_prod['vpcs'][0]['id'] }}"
  sg-0c921b43063fcc0ea:
    description: creating security group VM-sealbastion-infra-BastionSecurityGroup-16ZX1LD2EQX3Y
    group_id: sg-0c921b43063fcc0ea
    group_name: VM-sealbastion-infra-BastionSecurityGroup-16ZX1LD2EQX3Y
    rules:
    - cidr_ip: 209.131.62.115/32
      from_port: 22
      proto: tcp
      to_port: 22
    rules_egress:
    - cidr_ip: 0.0.0.0/0
      from_port: all
      proto: all
      to_port: all
    tags:
      Application: bastion
      Environment: infra
      Name: VM-sealbastion-infra-sg
      Owner: yourteam@oath.com
      Stack: bastion
    vpc_id: "{{ vpc_bastion['vpcs'][0]['id'] }}"
  sg-0d05484e2315fc741:
    description: creating security group VM-seal-Prod-SG-LB
    group_id: sg-0d05484e2315fc741
    group_name: VM-seal-Prod-SG-LB
    rules:
    - cidr_ip: 34.210.183.158/32
      from_port: 0
      proto: tcp
      to_port: 65535
    - cidr_ip: 52.35.163.8/32
      from_port: 0
      proto: tcp
      to_port: 65535
    - cidr_ip: 99.80.67.54/32
      from_port: 0
      proto: tcp
      to_port: 65535
    - cidr_ip: 35.165.99.123/32
      from_port: 0
      proto: tcp
      to_port: 65535
    - cidr_ip: 34.209.16.31/32
      from_port: 0
      proto: tcp
      to_port: 65535
    rules_egress:
    - cidr_ip: 0.0.0.0/0
      from_port: all
      proto: all
      to_port: all
    tags:
      Name: VM-seal-Prod-SG-LB
    vpc_id: "{{ vpc_prod['vpcs'][0]['id'] }}"
