---
 - name: testing aws 

   hosts: localhost 
   connection: local
 

   tags: test

   roles:
    - vpc
    - subnet
    - igw
    - nat
    - route
    - sg
    - acl
    - ami
    - volume
    - snapshot
    - ec2
     
    
