---
      - name: Get Linux AMI ID
        ec2_ami_facts:
         region: "{{ region }}"
         filters:
          "tag:Name": 'JUMPHOST-IP'
        register: linux_ami

      - name: Get Git AMI ID
        ec2_ami_facts:
         region: "{{ region }}"
         filters:
          "tag:Name": 'GHE-IP'
        register: ghe_ami


      - name: GHE AMI
        debug:
          var: ghe_ami


      - name: Linux AMI
        debug:
         var: linux_ami
